export const profileActivity =[
    
        {
          id: 1,
          avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
          username: "mynameismya",
          time: "17h",
          org: "marchofdimes",
          orgUrl: "/profile",
          text: `The quick, brown fox jumps over a lazy dog.\nDJs flock by when MTV ax quiz prog. Junk`,
          imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
          likes: 2,
          comments: 0,
          shares: 3,
        },
        {
          id: 2,
          avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
          username: "mynameismya",
          time: "1d",
          org: "feedthehungry",
          orgUrl: "/profile",
          text: `Had a great time volunteering at the food bank today! So many smiles and so much hope.`,
          imageUrl: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=600&q=80",
          likes: 5,
          comments: 1,
          shares: 0,
        },
        {
          id: 3,
          avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
          username: "mynameismya",
          time: "2d",
          org: "greenearth",
          orgUrl: "/profile",
          text: `Excited to join the Green Earth clean-up event this weekend! Let's make a difference together. 🌱`,
          likes: 8,
          comments: 2,
          shares: 1,
        },
        {
          id: 4,
          avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
          username: "mynameismya",
          time: "3d",
          org: "animalrescue",
          orgUrl: "/profile",
          text: `Met some adorable pups at the shelter. Please consider adopting or fostering if you can! 🐶❤️`,
          imageUrl: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=600&q=80",
          likes: 12,
          comments: 3,
          shares: 4,
        },
      
]


export const popularPosts = [
{
  id: 14,
  avatarUrl: "https://randomuser.me/api/portraits/women/28.jpg",
  username: "sophiahope",
  time: "3h",
  org: "localfoodbank",
  orgUrl: "/profile",
  text: `Just finished organizing food packages for 50 families this weekend! Every donation counts and makes a real difference in our community. Thank you to all our amazing volunteers! 🙏✨`,
  imageUrl: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80",
  likes: 12,
  comments: 0,
  shares: 3,
},
{
  id: 5,
  avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
  username: "johnnydoe",
  time: "4d",
  org: "youth4change",
  orgUrl: "/profile",
  text: `Just wrapped up an amazing youth leadership workshop! So proud of everyone who participated.`,
  imageUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80",
  likes: 15,
  comments: 4,
  shares: 2,
},
{
  id: 6,
  avatarUrl: "https://randomuser.me/api/portraits/women/55.jpg",
  username: "sarahsmiles",
  time: "5d",
  org: "cleanwaternow",
  orgUrl: "/profile",
  text: `We distributed clean water kits to over 100 families this week. Thank you to all our volunteers! 💧`,
  imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
  likes: 22,
  comments: 5,
  shares: 6,
},
{
  id: 7,
  avatarUrl: "https://randomuser.me/api/portraits/men/54.jpg",
  username: "mikegreen",
  time: "6d",
  org: "treeplanters",
  orgUrl: "/profile",
  text: `Planted 200 trees this weekend! Let's keep making our city greener. 🌳`,
  imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
  likes: 30,
  comments: 7,
  shares: 10,
},
{
  id: 8,
  avatarUrl: "https://randomuser.me/api/portraits/women/60.jpg",
  username: "emilywrites",
  time: "1w",
  org: "literacyforall",
  orgUrl: "/profile",
  text: `Hosted a book drive for local schools. Thank you to everyone who donated books! 📚`,
  imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80",
  likes: 18,
  comments: 2,
  shares: 3,
}]

// Additional posts for Load More functionality
export const morePostsToLoad = [
{
  id: 9,
  avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
  username: "alexcares",
  time: "1w",
  org: "homelesshelp",
  orgUrl: "/profile",
  text: `Helped serve meals at the homeless shelter yesterday. Every small act of kindness makes a difference! 🤝`,
  imageUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=600&q=80",
  likes: 25,
  comments: 6,
  shares: 8,
},
{
  id: 10,
  avatarUrl: "https://randomuser.me/api/portraits/women/72.jpg",
  username: "jennyhope",
  time: "1w",
  org: "cancersupport",
  orgUrl: "/profile",
  text: `Participated in the charity walk for cancer research. Together we can find a cure! 💜`,
  imageUrl: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=600&q=80",
  likes: 35,
  comments: 8,
  shares: 12,
},
{
  id: 11,
  avatarUrl: "https://randomuser.me/api/portraits/men/43.jpg",
  username: "davidgives",
  time: "2w",
  org: "seniorsupport",
  orgUrl: "/profile",
  text: `Spent the afternoon reading to seniors at the care home. Their stories are truly inspiring! 👴👵`,
  likes: 20,
  comments: 4,
  shares: 5,
},
{
  id: 12,
  avatarUrl: "https://randomuser.me/api/portraits/women/38.jpg",
  username: "mariahelpss",
  time: "2w",
  org: "childwelfare",
  orgUrl: "/profile",
  text: `Organized a toy drive for underprivileged children. The joy on their faces was priceless! 🧸`,
  imageUrl: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=600&q=80",
  likes: 42,
  comments: 10,
  shares: 15,
}]
