const categoryColors = {
    Animals: { text: "#E36414", background: "#FFE9DC" },
    Arts: { text: "#FF6B6B", background: "#FFECEC" },
    Community: { text: "#06D6A0", background: "#D6FFF1" },
    Education: { text: "#FFB84D", background: "#FFF3E0" },
    Environment: { text: "#6A994E", background: "#E8F4E4" },
    Food: { text: "#FF9F1C", background: "#FFF2E0" },
    General: { text: "#ADB5BD", background: "#F4F5F6" },
    Global: { text: "#48CAE4", background: "#E0F7FD" },
    Health: { text: "#D62828", background: "#FFE5E5" },
    Housing: { text: "#8D6E63", background: "#EFE6E3" },
    Jobs: { text: "#6C757D", background: "#F1F3F5" },
    Legal: { text: "#FFBE0B", background: "#FFF8E0" },
    Membership: { text: "#5E6472", background: "#ECEEF2" },
    Mental: { text: "#9D4EDD", background: "#F3E6FF" },
    Philanthropy: { text: "#FF006E", background: "#FFE0ED" },
    Public: { text: "#2A9D8F", background: "#DCF4F1" },
    Relief: { text: "#F94144", background: "#FFE3E3" },
    Religion: { text: "#E9C46A", background: "#FFF9E5" },
    Research: { text: "#3A86FF", background: "#E3EFFF" },
    Rights: { text: "#780000", background: "#F8E0E0" },
    Science: { text: "#023E8A", background: "#E0E9F8" },
    Services: { text: "#3F37C9", background: "#E8E6FF" },
    Society: { text: "#577590", background: "#EAF0F5" },
    Sports: { text: "#90BE6D", background: "#EEF7E9" },
    Wellness: { text: "#F28482", background: "#FFEAE9" },
    Youth: { text: "#4CC9F0", background: "#E0F7FF" },
  };
  
  export default categoryColors;
  