import { useQuery } from "@tanstack/react-query";
import { Loader2 } from "lucide-react";
import NewSuggestedCollectives from "@/components/newHome/NewSuggestedCollectives";
import NewFeaturedNonprofits from "@/components/newHome/NewFeaturedNonprofits";
import HelloGreeting from "@/components/newHome/HelloGreeting";
import MyDonationBoxCard from "@/components/newHome/MyDonationBoxCard";
import CollectiveCarouselCard from "@/components/newHome/CollectiveCarouselCard";
import CommunityUpdates from "@/components/newHome/CommunityUpdates";
import ExploreCards from "@/components/newHome/ExploreCards";
import ProfileNavbar from "@/components/profile/ProfileNavbar";
import { getCollectives, getCauses, getJoinCollective } from "@/services/api/crwd";
import { getDonationBox } from "@/services/api/donation";
import { getPosts } from "@/services/api/social";
import { useAuthStore } from "@/stores/store";
import GuestHome from "@/components/GuestHome";

export default function NewHome() {
    const { user, token } = useAuthStore();

    // Fetch collectives data using React Query
    const { data: collectivesData, isLoading: collectivesLoading } = useQuery({
        queryKey: ["collectives"],
        queryFn: getCollectives,
        enabled: true,
    });

    // Fetch nonprofits/causes data using React Query
    const { data: nonprofitsData, isLoading: nonprofitsLoading } = useQuery({
        queryKey: ["nonprofitts"],
        queryFn: getCauses,
        enabled: true,
    });

    // Fetch donation box data
    const { data: donationBoxData, isLoading: donationBoxLoading } = useQuery({
        queryKey: ["donationBox", user?.id],
        queryFn: getDonationBox,
        enabled: !!user?.id && !!token?.access_token,
    });

    // Fetch joined collectives data
    const { data: joinedCollectivesData, isLoading: joinedCollectivesLoading } = useQuery({
        queryKey: ["joined-collectives", user?.id],
        queryFn: () => getJoinCollective(user?.id?.toString() || ""),
        enabled: !!user?.id && !!token?.access_token,
    });

    // Fetch community updates (posts)
    const { data: postsData, isLoading: postsLoading } = useQuery({
        queryKey: ["posts", "community"],
        queryFn: () => getPosts("", "", 1),
        enabled: !!token?.access_token,
    });

    // Transform API data to match component's expected format
    const transformedCollectives =
        collectivesData?.results?.map((collective: any) => {
            const founderName = collective.created_by
                ? `${collective.created_by.first_name || ""} ${collective.created_by.last_name || ""
                    }`.trim()
                : "Unknown";

            return {
                id: collective.id,
                name: collective.name || "Unknown Collective",
                iconColor: undefined, // Will be auto-generated by component
                founder: {
                    name: founderName,
                    profile_picture: collective.created_by?.profile_picture || "",
                },
                nonprofit_count:
                    collective.causes_count ||
                    collective.supported_causes_count ||
                    collective.cause_count ||
                    0,
                description: collective.description || "No description available",
            };
        }) || [];

    // Transform nonprofits data to match component's expected format
    const transformedNonprofits =
        nonprofitsData?.results?.map((nonprofit: any) => ({
            id: nonprofit.id,
            name: nonprofit.name || "Unknown Nonprofit",
            image: nonprofit.image || "",
            description: nonprofit.mission || nonprofit.description || "",
            mission: nonprofit.mission || "",
        })) || [];

    // Transform donation box data
    const donationBoxInfo = donationBoxData
        ? {
            monthlyAmount: donationBoxData.monthly_amount || donationBoxData.amount || 10,
            causeCount:
                (donationBoxData.attributing_causes?.length || 0) +
                (donationBoxData.attributing_collectives?.length || 0),
        }
        : null;

    // Transform joined collectives data for carousel
    const transformedJoinedCollectives =
        joinedCollectivesData?.data?.map((item: any) => {
            const collective = item.collective || item;
            return {
                id: collective.id,
                name: collective.name || "Unknown Collective",
                memberCount: collective.member_count || 0,
                yearlyAmount: collective.yearly_donation_amount || collective.total_donations || 2340,
                causeCount: collective.causes_count || collective.supported_causes_count || 3,
                role: item.role || "Member",
                image: collective.cover_image || collective.avatar || collective.image || collective.created_by?.profile_picture || "",
            };
        }) || [];

    // Transform posts data for community updates
    const transformedCommunityUpdates =
        postsData?.results?.slice(0, 5).map((post: any) => ({
            id: post.id,
            user: {
                name: post.user?.first_name && post.user?.last_name
                    ? `${post.user.first_name} ${post.user.last_name}`
                    : post.user?.username || "Unknown User",
                username: post.user?.username || "unknown",
                avatar: post.user?.profile_picture || "",
            },
            collective: post.collective
                ? {
                    name: post.collective.name || "Unknown Collective",
                }
                : undefined,
            content: post.content || post.text || "",
            timestamp: post.created_at || post.timestamp,
        })) || [];


    if (!user?.id) {
        return <GuestHome />;
    }

    return (
        <div className="">
            <ProfileNavbar
                title="Home"
                showMobileMenu={true}
                showDesktopMenu={true}
                showBackButton={false}
            />
                {/* Main Content - Takes full width on mobile, 12 columns on desktop */}
                    <div className="bg-gradient-to-r from-blue-50 via-purple-50 to-pink-50 px-10 py-6">
                        {/* Personalized Greeting */}
                        <HelloGreeting />

                        {/* My Donation Box Card */}
                        {token?.access_token && (
                            donationBoxLoading ? (
                                <div className="flex items-center justify-center py-8 W-[200px]">
                                    <Loader2 className="h-6 w-6 animate-spin" />
                                </div>
                            ) : donationBoxInfo ? (
                                <MyDonationBoxCard
                                    monthlyAmount={donationBoxInfo.monthlyAmount}
                                    causeCount={donationBoxInfo.causeCount}
                                />
                            ) : null
                        )}

                        {/* Collective Carousel Card */}
                        {token?.access_token && (
                            joinedCollectivesLoading ? (
                                <div className="flex items-center justify-center py-8 max-w-[200px]">
                                    <Loader2 className="h-6 w-6 animate-spin" />
                                </div>
                            ) : (
                                <CollectiveCarouselCard collectives={transformedJoinedCollectives} />
                            )
                        )}

                        {/* Explore Cards */}

                        </div>

            <div className="md:grid md:grid-cols-12 md:gap-6 md:pt-6 md:px-6">
                <div className="md:col-span-12">
                        

                        {/* Featured Nonprofits Section */}
                        {nonprofitsLoading ? (
                            <div className="flex items-center justify-center py-8">
                                <Loader2 className="h-6 w-6 animate-spin" />
                            </div>
                        ) : (
                            <NewFeaturedNonprofits
                                nonprofits={transformedNonprofits}
                                seeAllLink="/search"
                            />
                        )}

                        {/* Suggested Collectives Section */}
                        {collectivesLoading ? (
                            <div className="flex items-center justify-center py-8">
                                <Loader2 className="h-6 w-6 animate-spin" />
                            </div>
                        ) : (
                            <NewSuggestedCollectives
                                collectives={transformedCollectives}
                                seeAllLink="/search"
                            />
                        )}



                        {/* Community Updates Section */}
                        {token?.access_token && (
                            postsLoading ? (
                                <div className="flex items-center justify-center py-8">
                                    <Loader2 className="h-6 w-6 animate-spin" />
                                </div>
                            ) : (
                                <CommunityUpdates updates={transformedCommunityUpdates} />
                            )
                        )}
                    </div>
                </div>
                <ExploreCards />

            </div>
            );
}

