import { useQuery } from "@tanstack/react-query";
import { Loader2 } from "lucide-react";
import NewSuggestedCollectives from "@/components/newHome/NewSuggestedCollectives";
import NewFeaturedNonprofits from "@/components/newHome/NewFeaturedNonprofits";
import ProfileNavbar from "@/components/profile/ProfileNavbar";
import { getCollectives, getCauses } from "@/services/api/crwd";

export default function NewHome() {
  // Fetch collectives data using React Query
  const { data: collectivesData, isLoading: collectivesLoading } = useQuery({
    queryKey: ["collectives"],
    queryFn: getCollectives,
    enabled: true,
  });

  // Fetch nonprofits/causes data using React Query
  const { data: nonprofitsData, isLoading: nonprofitsLoading } = useQuery({
    queryKey: ["nonprofitts"],
    queryFn: getCauses,
    enabled: true,
  });

  // Transform API data to match component's expected format
  const transformedCollectives =
    collectivesData?.results?.map((collective: any) => {
      const founderName = collective.created_by
        ? `${collective.created_by.first_name || ""} ${
            collective.created_by.last_name || ""
          }`.trim()
        : "Unknown";

      return {
        id: collective.id,
        name: collective.name || "Unknown Collective",
        iconColor: undefined, // Will be auto-generated by component
        founder: {
          name: founderName,
          profile_picture: collective.created_by?.profile_picture || "",
        },
        nonprofit_count:
          collective.causes_count ||
          collective.supported_causes_count ||
          collective.cause_count ||
          0,
        description: collective.description || "No description available",
      };
    }) || [];

  // Transform nonprofits data to match component's expected format
  const transformedNonprofits =
    nonprofitsData?.results?.map((nonprofit: any) => ({
      id: nonprofit.id,
      name: nonprofit.name || "Unknown Nonprofit",
      image: nonprofit.image || "",
      description: nonprofit.mission || nonprofit.description || "",
      mission: nonprofit.mission || "",
    })) || [];

  return (
    <div className="">
      <ProfileNavbar
        title="Home"
        showMobileMenu={true}
        showDesktopMenu={true}
        showBackButton={false}
      />
      <div className="md:grid md:grid-cols-12 md:gap-6 md:pt-6 md:px-6">
        {/* Main Content - Takes full width on mobile, 12 columns on desktop */}
        <div className="md:col-span-12">
          {/* Featured Nonprofits Section */}
          {nonprofitsLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin" />
            </div>
          ) : (
            <NewFeaturedNonprofits
              nonprofits={transformedNonprofits}
              seeAllLink="/search"
            />
          )}

          {/* Suggested Collectives Section */}
          {collectivesLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin" />
            </div>
          ) : (
            <NewSuggestedCollectives
              collectives={transformedCollectives}
              seeAllLink="/search"
            />
          )}
        </div>
      </div>
    </div>
  );
}

